package dev.hiba550.smartprofiler.config;

/**
 * Types of configuration changes that can occur
 * 
 * @author Hiba550
 * @version 1.0.0
 * @since MC 1.21.5
 */
public enum ConfigChangeType {
    // General settings
    ENABLED_CHANGED,
    REALTIME_MONITORING_CHANGED,
    BOTTLENECK_ANALYSIS_CHANGED,
    DATABASE_CHANGED,
    COLLECTION_FREQUENCY_CHANGED,
    
    // Overlay settings
    OVERLAY_ENABLED_CHANGED,
    OVERLAY_MODE_CHANGED,
    OVERLAY_POSITION_CHANGED,
    OVERLAY_OPACITY_CHANGED,
    OVERLAY_UPDATE_RATE_CHANGED,
    SHOW_GRAPHS_CHANGED,
    SHOW_WARNINGS_CHANGED,
    ANIMATIONS_CHANGED,
    
    // Threshold settings
    FPS_THRESHOLD_CHANGED,
    MEMORY_THRESHOLD_CHANGED,
    CHUNK_THRESHOLD_CHANGED,
    ENTITY_THRESHOLD_CHANGED,
    RENDER_THRESHOLD_CHANGED,
    NETWORK_THRESHOLD_CHANGED,
    
    // Analysis settings
    SERVER_MONITORING_CHANGED,
    MEMORY_LEAK_DETECTION_CHANGED,
    GPU_DETECTION_CHANGED,
    OPTIMIZATION_SUGGESTIONS_CHANGED,
    ANALYSIS_WINDOW_CHANGED,
    TREND_SENSITIVITY_CHANGED,
    
    // Notification settings
    CHAT_NOTIFICATIONS_CHANGED,
    SOUND_NOTIFICATIONS_CHANGED,
    TOAST_NOTIFICATIONS_CHANGED,
    NOTIFICATION_COOLDOWN_CHANGED,
    CRITICAL_ONLY_CHANGED,
    
    // Storage settings
    DATA_PERSISTENCE_CHANGED,
    DATA_RETENTION_CHANGED,
    DATABASE_SIZE_CHANGED,
    AUTO_CLEANUP_CHANGED,
    CSV_EXPORT_CHANGED,
    
    // Advanced settings
    DEBUG_LOGGING_CHANGED,
    EXPERIMENTAL_FEATURES_CHANGED,
    THREAD_COUNT_CHANGED,
    JFR_INTEGRATION_CHANGED,
    NATIVE_MEMORY_CHANGED,
    BUFFER_SIZE_CHANGED,
    
    // Meta changes
    CONFIG_RESET,
    CONFIG_RELOADED,
    CONFIG_SAVED
}